name: Python App Test
on:
    pull_request:
        branches: main
    push:
        branches: main
jobs:
    test:
        runs-on: ubuntu-latest
        defaults: 
            run: 
                working-directory: ./
        strategy:
            matrix:
                python-version: [3.9, "3.10", 3.11]
        steps:
            - uses: actions/checkout@v3
            - name: Setup python
              uses: actions/setup-python@v4
              with: 
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ./requirements.txt
            
            - name: Install develpment dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ./requirements/dvpt_dependencies.txt
            
            - name: Testing code with Pytest
              run: |
                python -c "import sys; print(sys.path)"
                # pytest tests/
